[package]
name = "risc0_groth16_aggregation"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
groth16 = { path = "../../../groth16" }
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
